In [19]:
import pandas as pd

In [20]:
import numpy as np

In [21]:
from sklearn.model_selection import train_test_split


In [22]:
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC, LinearSVC

In [24]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
import pickle

In [25]:
data = pd.read_csv('final_data.csv')
data['crop_type'].unique()

array(['carrot', 'coconut', 'cotton', 'groundnut', 'melon', 'millet',
       'potatoes', 'rice', 'vegetable', 'wheat'], dtype=object)

In [26]:
mapping = {'carrot': 1, 'coconut': 2, 'cotton': 3, 'groundnut': 4, 'melon': 5, 'millet': 6, 'potatoes': 7, 'rice': 8,
           'vegetable': 9, 'wheat': 10}
data['crop_type'] = data['crop_type'].map(mapping)

In [27]:

data['Soil_type'].unique()
mapping = {'clay': 1, 'Sandy': 2, 'loamy': 3}
data['Soil_type'] = data['Soil_type'].map(mapping)

In [28]:
X = data.drop('crop_type', axis=1).values
y = data.crop_type.values

In [29]:
# splitting data as X_train and X_test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,random_state = 0)



In [30]:

# Feature Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [31]:
model = SVC(C=2.0, cache_size=200, class_weight=None, coef0=0.5, decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf', max_iter=-1, probability=False, random_state= 1000, shrinking=True, tol=0.11, verbose=False)
#model = SVC(kernel='linear', decision_function_shape='ovo', C = 0.02, gamma='scale', cache_size=200, coef0=0.0)
model.fit(X_train,y_train)

SVC(C=2.0, coef0=0.5, gamma='auto', random_state=1000, tol=0.11)

In [32]:
"""with open('crop_recommender.pkl', 'wb') as f:
    pickle.dump(model, f)

pickle_in = open('crop_recommender.pkl', 'rb')
clf = pickle.load(pickle_in)"""
    

"with open('crop_recommender.pkl', 'wb') as f:\n    pickle.dump(model, f)\n\npickle_in = open('crop_recommender.pkl', 'rb')\nclf = pickle.load(pickle_in)"

In [33]:
prediction_svm=model.predict(X_test)

In [34]:
#print(accuracy_score(y_true, y_pred))
print(accuracy_score(y_test, prediction_svm))


0.56


In [35]:
cm = confusion_matrix(y_test, prediction_svm)
print(cm)

[[ 0  0  0  0  0  0  2 11  0  0]
 [ 0  0  0  0 11  0  0  0  0  0]
 [ 0  0  0 11  0  0  0  0  0  1]
 [ 0  0  0 39  0  0  0  0  0  0]
 [ 0  0  0  0 38  0  0  0  0  0]
 [ 0  0  0  5  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  4 11  0  0]
 [ 0  0  0  0  0  0  3 31  0  0]
 [ 0  0  0 12  0  0  0  0  0  2]
 [ 0  0  0 19  0  0  0  0  0  0]]
